version: '3.8'

services:
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - wp

  mailpit:
    image: axllent/mailpit
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - wp

networks:
  wp:
    name: ${WP_ENV_CONTAINER_HASH}_default
    external: true
