services:
  adminer:
    image: adminer
    container_name: ${WP_ENV_CONTAINER_HASH}-adminer-1
    ports:
      - 8080:8080
    networks:
      - wp

  mailpit:
    image: axllent/mailpit
    container_name: ${WP_ENV_CONTAINER_HASH}-mailpit-1
    ports:
      - 1025:1025
      - 8025:8025
    networks:
      - wp

networks:
  wp:
    name: ${WP_ENV_CONTAINER_HASH}_default
    external: true
